apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksdemo-6790"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksdemo-6790"
  template:
    metadata:
      labels:
        app: "aksdemo-6790"
    spec:
      containers:
        - name: "aksdemo-6790"
          image: "acrdemoaks17.azurecr.io/aksdemo"
          ports:
          - containerPort: 80